Adding functions to vmtools
Adding is_admin()
Modifying createvm, delvm, and takesnapshot to use is_admin().
Renaming test/test-uid to test/test-vmtools

diff --git a/install/opt/vmtools/bin/delvm b/install/opt/vmtools/bin/delvm
--- a/install/opt/vmtools/bin/delvm
+++ b/install/opt/vmtools/bin/delvm
@@ -8,32 +8,68 @@
 # Website::   http://ktechsystems.com
 ##############################################################################
 
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+##############################################
 # Functions
+#
+
+source $SCRIPT_DIR/__vmtools.sh
+
+
+# Local Functions
 
 usage() {
   echo "Usage: sudo `basename $0` {vm-name}"
 }
 
-# Check for proper number of command line args. -----
-expected_args=1
-e_badargs=65
-if [ $UID -ne 0 ] || [ $# -ne $expected_args ]
-then
+# Check if user has sudo privledges.
+if ( ! is_admin ); then
+    echo "Must run as sudo or root."
     usage
-    exit $e_badargs
+    exit $E_NOTAUTHORIZED
 fi
 
+# Check for proper number of command line args.
+expected_args=1
+if [ $# -ne $expected_args ]
+then
+    usage
+    exit $E_BADARGS
+fi
+
+##############################################
+# Delete VM
+#
 
 # Delete a VM
 (VBoxManage unregistervm $1 --delete)
 
+
+##############################################
+# Clean up other files
+#
+
 # Remove the upstart conf file if it exists.
 upstart_conf = "/etc/init/vm-$1.conf"
-if [[ -f $upstart_conf ]] then
-  echo "removing $1"
+if [ -f $upstart_conf ] then
+  echo "removing $upstart_conf"
   rm $upstart_conf
 else
   echo "not found: $upstart_conf"
 fi
 
+# Remove the remote upstart conf file if it exists.
+upstart_conf = "/etc/init/vm-$1-rd.conf"
+if [ -f $upstart_conf ] then
+  echo "removing $upstart_conf"
+  rm $upstart_conf
+else
+  echo "not found: $upstart_conf"
+fi
 
+vm_root=$(vm_root_dir $1)
+if [ -d $vm_root ]; then
+    echo "Deleting dir: $vm_root"
+    #rm -r $vm_root
+fi
diff --git a/install/opt/vmtools/bin/takesnapshot b/install/opt/vmtools/bin/takesnapshot
--- a/install/opt/vmtools/bin/takesnapshot
+++ b/install/opt/vmtools/bin/takesnapshot
@@ -26,12 +26,16 @@ usage() {
 # Validation Checks
 #
 
-# Set required UID based on the OS.
-required_uid=$(required_uid)
+# Check if user has sudo privledges.
+if ( ! is_admin ); then
+    echo "Must run as sudo or root."
+    usage
+    exit $E_NOTAUTHORIZED
+fi
 
 # Check for proper number of command line args.
 expected_args=1
-if [ $UID -ne $required_uid ] || [ $# -lt $expected_args ]
+if [ $# -ne $expected_args ]
 then
     usage
     exit $E_BADARGS
@@ -48,12 +52,34 @@ snap_name=${2:-$dt_name}               # Default to 'snapshot-YYYY-MM-DD'
 
 
 ##############################################
+# Pause VM if running
+#
+
+if ( (is_vm_running $vm_name) ); then
+    echo "  Pausing VM prior to snapshot"
+    (VBoxManage controlvm $vm_name pause)
+    vm_is_paused=true
+else
+    vm_is_paused=false
+fi
+
+
+##############################################
 # Take a snapshot
 #
 
-if ( VBoxManage snapshot $vm_name take $snap_name ); then
+if ( (VBoxManage snapshot $vm_name take $snap_name) ); then
   echo "Snapshot taken: $snap_name"
 else
-  exit $E_BADARGS
+  echo "Error: There was a problem taking the snapshot"
 fi
 
+
+##############################################
+# Resume VM if paused
+#
+
+if [[ $vm_is_paused == true ]]; then
+    echo "  Resuming VM post snapshot"
+    (VBoxManage controlvm $vm_name resume)
+fi
